### ISSUE TITLE
Questions about droppyjs

### ISSUE THREAD

**Issue by henriberisha** [droppyjs/droppy#104]
Hello,

In the past i have used "droppy" and recently i came across this new version. I am thinking to install your version but i wanted to gather some information before I do so. 

Is `droppyjs` based on the old droppy?  https://github.com/silverwind/droppy
If so what are the new updates?
Is it free to use? 

Thank you very much

**Comment by markhughes** [comment]
Hi there! 

Yes it is. It is compatible and you can move to it by uninstalling the old version and installing the new one. (Check README) 

Mostly bugs addressed and modernising code, I am currently working on user permissions (e.g. read-only mode). 

It is free and open source as before :)
