### ISSUE TITLE
Feature request: configure created file/directory owner/group and permissions

### ISSUE THREAD

**Issue by M1CK431** [droppyjs/droppy#107]
Hi 👋🏼 

I need a way or another to configure the created file and directory owner/group and permissions.

Currently, I'm thinking about 2 solutions (which are not mutually exclusive):
- add a few options in the config file:
  - `createdFileMode` (default: `644`)
  - `createdDirMode` (default: `755`)
  - `uploadedFileMode` (default: `createdFileMode` value)
  - `uploadedDirMode` (default `createdDirMode` value)
  - `createdFileUser` (default: process user)
  - `createdFileGroup` (default: process user)
- for more complexe scenario, add some events handlers as options in the config file:
  - `onCreateFile` (no default)
  - `onCreateDir` (no default)
  - `onUploadFile` (default: `onCreateFile` value)
  - `onUploadDir` (default: `onCreateDir` value)
  - ... other events handlers you think useful too like `onRenameFile`, `onDeleteFile`, etc...

Obviously, events handlers must be executables binaries/scripts and receive the related file(s) or directory(-ies) as parameter(s).

As myself a JS developer, I would be happy to open a PR with such feature if contributions are welcome.
WDYT @markhughes ?

**Comment by M1CK431** [comment]
Just trying to work in this project... the setup seems so hard... lerna... nx... but why??
well, not sure it's for me... sorry 😢

**Comment by markhughes** [comment]
Hey @M1CK431 sorry you struggled with the monorepo! I've been meaning to remove lerna/nx and just move to yarn workspaces instead, but its a lot to switch over! 

If you need a hand I'm more than happy to help you out.

To initialise lerna (one time process) just run:

```
npm run lerna bootstrap
```

Then all the packages will be mapped. 

From here you can go ahead and start droppy with:

```
yarn start
```

If you make changes to cached items (e.g. tempaltes), etc, you will want to pass `--dev` so the cache rebuilds 

```
yarn start --dev
```

**Comment by M1CK431** [comment]
Hi @markhughes , thanks for your reply and help.
Perhaps I will give it a try a bit latter.

> I've been meaning to remove lerna/nx and just move to yarn workspaces instead, but its a lot to switch over!

I where using `yarn` previously but switch to `pnpm` which is a far better package manager. I urge you to prefer it instead.
