### ISSUE TITLE
Removing files broken since excluding rimraf

### ISSUE THREAD

**Issue by devbranch-vadym** [droppyjs/droppy#31]
It seems like removing files doesn't work since https://github.com/silverwind/droppy/commit/13d70bc619c67f6733222405d4d2911f26fcef52 .

Originally the code was using `rimraf` but then it was replaced with `fs.rmdir` used for both files and directories.

When you delete files from UI they appears to be removed but actually they remain on the server.

**Comment by markhughes** [comment]
Thanks for tackling this one so quickly!
