### ISSUE TITLE
The Delete button is really dangerous

### ISSUE THREAD

**Issue by Tronic** [droppyjs/droppy#35]
There is no confirmation when the delete button is pressed, and even entire folders can be deleted with a single click. Since the button is between download and actions buttons, on each row, misclicks are all too easy.

I suggest reworking the logic:
1. Remove per-file action buttons, add buttons on title toolbar instead (similar to other file managers)
2. Add a confirmation to deletion (the dialog should display how many files etc. are being removed)
3. Allow selection of multiple files and select all, such that bulk deletion/download/etc. become feasible

Previously reported at https://github.com/silverwind/droppy/issues/391 but never fixed, closely related to #16 too.

**Comment by markhughes** [comment]
Good idea. Thank you!
