### ISSUE TITLE
Latest from yarn is 0.1.0

### ISSUE THREAD

**Issue by Tronic** [droppyjs/droppy#42]
Am I missing something or have you not pushed the latest releases?

```
yarn global add @droppyjs/cli
droppy -v
0.1.0
```

Expected: 0.2.1

**Comment by markhughes** [comment]
Hey @Tronic looks like something went a little odd with publishing. I'll check it out and try again - thanks!

**Comment by markhughes** [comment]
I've now published 0.2.2, thanks for pointing that out!
