### ISSUE TITLE
Docker Issues

### ISSUE THREAD

**Issue by markhughes** [droppyjs/droppy#57]
### Discussed in https://github.com/droppyjs/droppy/discussions/44

<div type='discussions-op-text'>

<sup>Originally posted by **j1cs** October  6, 2021</sup>
I'm asking because the README says is broken.</div>

...

> I tried to use it but i gave me this error`bash: node: command not found` looks like the Dockerfile config doesn't have the node package.

**Comment by Nindouja** [comment]
Same for me; i couldn't find the latest version on the hub so i build and pushed from master (https://hub.docker.com/repository/docker/bancarel/droppy) Upon starting the only log I have is 
`bash: node: command not found`. 

Also, is it possible for you to push a version on docker hub on new releases ?

**Comment by markhughes** [comment]
@BancarelValentin you can use the canary version for the latest, I'm working towards a new release shortly 😄 

https://github.com/droppyjs/droppy/pkgs/container/droppy/96421426?tag=canary

**Comment by kirillzhosul** [comment]
I am deployed latest version to give a try for that project and it seems to be working fine

**Comment by markhughes** [comment]
great to hear, thanks!
