### ISSUE TITLE
unable to change file location

### ISSUE THREAD

**Issue by MuhannadYT** [droppyjs/droppy#68]
When I enter `droppy start -c D:\droppy\config -f D:\droppy\files`  for example,
droppy launches in `C:\Users\[username]\.droppy`

**Comment by markhughes** [comment]
hey @MuhannadYT can you share your version? 

```
droppy -v
```

**Comment by MuhannadYT** [comment]
0.2.8

**Comment by levouh** [comment]
Same thing happens for me on Linux (Ubuntu 22.04) using Node 18 - regardless of the `-c` and `-f` options I use, it will use `~/.droppy/`.

**Comment by levouh** [comment]
Is [this](https://github.com/droppyjs/droppy/blob/canary/packages/cli/lib/cli.js#L17) the issue? When parsing the arguments, it doesn't seem to specify that `configdir` or `filesdir` are even valid options?

---

Perhaps not - it [looks like ](https://www.npmjs.com/package/minimist) it should just pass through options as they are given if not declared.

Confirmed that the arguments are passed through verbatim by adding some `console.log` statements:

```
root@droppy:~# /usr/bin/droppy -c /mnt/nfs/server/droppy/config -f /mnt/nfs/server/droppy/files
{
  _: [],
  color: false,
  d: false,
  daemon: false,
  dev: false,
  c: '/mnt/nfs/server/droppy/config',
  f: '/mnt/nfs/server/droppy/files'
}
/mnt/nfs/server/droppy/config
/mnt/nfs/server/droppy/files
```

Further, it looks like `paths.get` is called before `paths.seed`:

```
root@droppy:~# /usr/bin/droppy -c /mnt/nfs/server/droppy/config -f /mnt/nfs/server/droppy/files
paths.get
/root/.droppy/config
/root/.droppy/files
paths.get
/root/.droppy/config
/root/.droppy/files
paths.get
/root/.droppy/config
/root/.droppy/files
paths.get
/root/.droppy/config
/root/.droppy/files
paths.get
/root/.droppy/config
/root/.droppy/files
paths.get
/root/.droppy/config
/root/.droppy/files
paths.get
/root/.droppy/config
/root/.droppy/files
paths.seed
/mnt/nfs/server/droppy/config
/mnt/nfs/server/droppy/files
```

---

Is it really just that `paths.get()` is called on the server start and not refreshed after `.seed()` is called?
