### ISSUE TITLE
Clicking on the "play" button on a mp3 file doesn't play the mp3 anymore like it used to.

### ISSUE THREAD

**Issue by gissehel** [droppyjs/droppy#9]
# Scenario

* Upload a mp3 on droppy
* Put the cursor over the file's icon. The icon change to a play button
* Click on that button

# Expected result

* The mp3 is playing, and a play bar appears in the bottom of the list view

# Actual result

* The mp3 is downloaded

# Analyse

I can't find why this is happening, but it's not browser related : I have tracked down the problem to a change between tag 11.1.0 and 12.0.0 by dichotomie.

I suppose the problem comes from a change in client.js, but except for indentation, most changes are:

* function moves across the file
* New js syntaxe like `'example ' + variable` replaced by `` `example ${variable}` ``

There an error in the console about volume, but I haven't been able to find the root of the problem yet.
If I find, I'll try to provide a PR for it.

**Comment by markhughes** [comment]
Resolved now!

**Comment by gissehel** [comment]
Great ! It works, Thanks !
