### ISSUE TITLE
Empty folders are ignored

### ISSUE THREAD

**Issue by vahtos** [droppyjs/droppy#92]
Empty directories are not uploaded (drag and drop and "upload folder from disk"). No error message is displayed, or in the console, the directories just never appear.

This includes directories which are empty, and nested in other directories that are not empty. In that case, only directories with files in them, and the files are uploaded. Interestingly, if you nest two empty directories, they are both ignored as well.

**Comment by vahtos** [comment]
Narrowed this down and found the culprit is [Uppie](https://www.npmjs.com/package/uppie):

> Empty directories are excluded from the results by all browsers as dictated by the spec.

I'm not sure what is meant by "the spec", but I think [this issue](https://github.com/silverwind/uppie/issues/13) gives more context for the reasoning:

> Some variants of the older APIs might allow them but I remember there is no cross-browser solution.

**Comment by markhughes** [comment]
This looks like an upstream issue, but it sounds like browser don't support it. So we'll need to have it resolved in Uppie (if possible), unless someone has an idea on how to handle this! 

Thanks for reporting!
